export const dataBotons = [
  {
    name: "zero",
    class: "gray borderBlack",
    title: "0",
    type: "number",
  },
  {
    name: "one",
    class: "gray",
    title: "1",
    type: "number",
  },
  {
    name: "two",
    class: "gray",
    title: "2",
    type: "number",
  },
  {
    name: "three",
    class: "gray",
    title: "3",
    type: "number",
  },
  {
    name: "four",
    class: "gray",
    title: "4",
    type: "number",
  },
  {
    name: "five",
    class: "gray",
    title: "5",
    type: "number",
  },
  {
    name: "six",
    class: "gray",
    title: "6",
    type: "number",
  },
  {
    name: "seven",
    class: "gray",
    title: "7",
    type: "number",
  },
  {
    name: "eight",
    class: "gray",
    title: "8",
    type: "number",
  },
  {
    name: "nine",
    class: "gray",
    title: "9",
    type: "number",
  },
  {
    name: "add",
    class: "grayLight",
    title: "+",
    type: "operation",
  },
  {
    name: "subtract",
    class: "grayLight",
    title: "-",
    type: "operation",
  },
  {
    name: "multiply",
    class: "grayLight",
    title: "*",
    type: "operation",
  },
  {
    name: "divide",
    class: "grayLight",
    title: "/",
    type: "operation",
  },
  {
    name: "decimal",
    class: "grayLight",
    title: ".",
    type: "number",
  },
  {
    name: "equals",
    class: "",
    title: "=",
    type: "result",
  },
  {
    name: "clear",
    class: "",
    title: "AC",
    type: "clear",
  },
];
